end-to-end testing test2
bookingcom/nanotube pull request #117
Opened 2021-02-08 22:14 UTC by dams

. fix current test1
. add test2

2021-02-09 10:36 UTC, avereha approved these changes

2021-02-09 12:18 UTC, grzkv requested changes
I am happy to see this PR in! However, it bloats the repo in two ways:

1. The number of files increases by a lot. This will increase the number of references in git, slowdown search, and indexing in IDEs.
2. Plain size of the repo.

Out of these, the first problem is more acute.

As a solution, I suggest to zip the testing files and unzip them when running the test.

@dams What do you think?

2021-02-09 15:00 UTC, dams commented
output is also compressed to save space. I've rebased and force push to avoid all the files to hit the repo

2021-02-09 15:07 UTC, grzkv commented
@dams Thanks for the update!

I've tried running the test in the clean repo and I get:
```
❯ make end-to-end-test 
cd test && ./run.sh

*** testing test1 ***

. starting nanotube

. starting receiver
./run.sh: line 20: ./receiver/receiver: No such file or directory
2021/02/09 16:03:57 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
{"level":"info","ts":1612883037.0116768,"caller":"in/listen.go:35","msg":"Launch: Opened TCP connection for listening.","ListenTCP":":2003"}

. starting sender
./run.sh: line 39: ./sender/sender: No such file or directory
```

Perhaps, it makes sense to add make target for the test utils and make the `end-to-end-test` dependent on it?

2021-02-12 16:40 UTC, grzkv approved these changes

2021-02-15 13:50 UTC, merged