observability: add rewrite_match_records metric
bookingcom/nanotube pull request #158
Opened 2022-03-29 13:48 UTC by azhiltsov

## What issue is this change attempting to solve?
nanotube allow to perform rewrites of incoming records
Currently there is no visibility over utilisation of this functionality

## How does this change solve the problem? Why is this the best approach?
This commit is adding rewrite_match_records prometheus
counter in order to gain visibility over rewrite rules
usage. The counter increases on every rewrite rule match
and does not track actual actions performed with matched
record.

## How can we be sure this works as expected?

Fixes #157

2022-03-29 14:30 UTC, grzkv commented on pkg/metrics/metrics.go
> +			Help:      "Counter of metics matched rewrite rules",
```suggestion
			Help:      "Number of metics that were matched by any of the rewrite rules",
```

2022-03-29 15:16 UTC, azhiltsov commented on pkg/rewrites/rewrites.go
> +			metrics.RewriteMatchRecords.Inc()
I think that is actually what we want.
I wanted to measure amount of work we actually do by having rewrite rules in place.
If one data point matches two rewrite rules - we actually do the work twice and this counter will clearly represent it.

2022-03-30 14:15 UTC, grzkv requested changes

2022-03-30 14:15 UTC, grzkv commented on pkg/rewrites/rewrites.go
> +			metrics.RewriteMatchRecords.Inc()
IMO having number of points matching the rules is more useful and *much* more clear. Also, this is not what the metric name and description say.
Also, there will be less performance overhead if we count points. Counting metrics is not cheap.
I'd prefer if we counted points, not "matches".

2022-03-31 10:22 UTC, grzkv commented
@azhiltsov Usually, it's not a good idea to name branches after issues. Because it only makes sense within GitHub and requires a look-up. Better give a short description. Plus, a number can both correspond to an issue and to a PR.

2022-03-31 10:22 UTC, grzkv commented
@azhiltsov Usually, it's not a good idea to name branches after issues. Because it only makes sense within GitHub and requires a look-up. Better give a short description. Plus, a number can both correspond to an issue and to a PR.

2022-03-31 14:54 UTC, closed without merging